ktor:
  port: 8080
  wait: true

mysql:
  host: ${MYSQL_HOST}
  user: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}

gateways:
  bacen:
    host: 'https://api.bcb.gov.br'
  chameidor:
    host: 'http://localhost:8081'

app-own-host: 'localhost:8080'
