-- Initial schema — the 7 tables production actually has today (index, index_value,
-- checking_account, bond, bond_order, bond_order_statement, bond_order_position). Generated by
-- ./gradlew :persistence:generateMigrationScript against those Exposed *Table objects, not
-- hand-written. `listed_asset`/`trade`/... and the allocation-engine tables were added to the
-- Exposed model well after this schema shipped, so they're deliberately NOT here — see V2 and V3
-- (backend/CLAUDE.md §7). The three seed rows are the fixed set of Brazilian rate indices this
-- app knows about (see IndexId).

CREATE TABLE IF NOT EXISTS `index` (id VARCHAR(10) PRIMARY KEY, created_at DATETIME(6) NOT NULL);

INSERT INTO `index` (id, created_at) VALUES ('CDI', NOW());
INSERT INTO `index` (id, created_at) VALUES ('IPCA', NOW());
INSERT INTO `index` (id, created_at) VALUES ('SELIC', NOW());

CREATE TABLE IF NOT EXISTS index_value (id INT AUTO_INCREMENT PRIMARY KEY, index_id VARCHAR(10) NOT NULL, `date` DATE NOT NULL, `value` DECIMAL(12, 8) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_index_value_index_id__id FOREIGN KEY (index_id) REFERENCES `index`(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE index_value ADD CONSTRAINT index_value_index_id_date_unique UNIQUE (index_id, `date`);
CREATE TABLE IF NOT EXISTS checking_account (id INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, `value` DECIMAL(8, 4) NOT NULL, index_id VARCHAR(10) NOT NULL, maturity_duration VARCHAR(5) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_checking_account_index_id__id FOREIGN KEY (index_id) REFERENCES `index`(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS bond (id INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, rate_type VARCHAR(10) NOT NULL, `value` DECIMAL(8, 4) NOT NULL, index_id VARCHAR(10) NULL, maturity_date DATE NOT NULL, checking_account_id INT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_bond_index_id__id FOREIGN KEY (index_id) REFERENCES `index`(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_bond_checking_account_id__id FOREIGN KEY (checking_account_id) REFERENCES checking_account(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE TABLE IF NOT EXISTS bond_order (id INT AUTO_INCREMENT PRIMARY KEY, bond_id INT NULL, checking_account_id INT NULL, `type` VARCHAR(20) NOT NULL, `date` DATE NOT NULL, amount DECIMAL(12, 2) NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_bond_order_bond_id__id FOREIGN KEY (bond_id) REFERENCES bond(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_bond_order_checking_account_id__id FOREIGN KEY (checking_account_id) REFERENCES checking_account(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX bond_order_bond_id_type ON bond_order (bond_id, `type`);
CREATE TABLE IF NOT EXISTS bond_order_statement (id INT AUTO_INCREMENT PRIMARY KEY, buy_order_id INT NOT NULL, sell_order_id INT NULL, `type` VARCHAR(20) NOT NULL, `date` DATE NOT NULL, amount DECIMAL(12, 2) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_bond_order_statement_buy_order_id__id FOREIGN KEY (buy_order_id) REFERENCES bond_order(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_bond_order_statement_sell_order_id__id FOREIGN KEY (sell_order_id) REFERENCES bond_order(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX bond_order_statement_buy_order_id_date ON bond_order_statement (buy_order_id, `date`);
ALTER TABLE bond_order_statement ADD CONSTRAINT bond_order_statement_buy_order_id_type_date_unique UNIQUE (buy_order_id, `type`, `date`);
CREATE TABLE IF NOT EXISTS bond_order_position (id INT AUTO_INCREMENT PRIMARY KEY, bond_order_id INT NOT NULL, `date` DATE NOT NULL, principal DECIMAL(14, 2) NOT NULL, yield DECIMAL(14, 2) NOT NULL, taxes DECIMAL(14, 2) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_bond_order_position_bond_order_id__id FOREIGN KEY (bond_order_id) REFERENCES bond_order(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
