-- Adds the listed-asset tracking tables (stocks/FIIs/ETFs/BDRs) — a later feature than V1's bond
-- and checking-account schema, so it ships as its own migration rather than folded into V1.
-- Generated by ./gradlew :persistence:generateMigrationScript, not hand-written.
CREATE TABLE IF NOT EXISTS listed_asset (id INT AUTO_INCREMENT PRIMARY KEY, ticker VARCHAR(12) NOT NULL, kind VARCHAR(10) NOT NULL, `name` VARCHAR(150) NOT NULL, b3_identifier VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL);
ALTER TABLE listed_asset ADD CONSTRAINT listed_asset_ticker_unique UNIQUE (ticker);
CREATE TABLE IF NOT EXISTS listed_asset_ticker_history (id INT AUTO_INCREMENT PRIMARY KEY, listed_asset_id INT NOT NULL, ticker VARCHAR(12) NOT NULL, effective_from DATE NOT NULL, effective_to DATE NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_listed_asset_ticker_history_listed_asset_id__id FOREIGN KEY (listed_asset_id) REFERENCES listed_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX listed_asset_ticker_history_ticker_effective_from ON listed_asset_ticker_history (ticker, effective_from);
CREATE TABLE IF NOT EXISTS trade (id INT AUTO_INCREMENT PRIMARY KEY, listed_asset_id INT NOT NULL, `date` DATE NOT NULL, quantity DECIMAL(18, 8) NOT NULL, price DECIMAL(12, 4) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_trade_listed_asset_id__id FOREIGN KEY (listed_asset_id) REFERENCES listed_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX trade_listed_asset_id_date ON trade (listed_asset_id, `date`);
CREATE TABLE IF NOT EXISTS corporate_action (id INT AUTO_INCREMENT PRIMARY KEY, listed_asset_id INT NOT NULL, `type` VARCHAR(20) NOT NULL, `date` DATE NOT NULL, ratio DECIMAL(18, 8) NULL, value_per_new_share DECIMAL(12, 4) NULL, new_ticker VARCHAR(12) NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_corporate_action_listed_asset_id__id FOREIGN KEY (listed_asset_id) REFERENCES listed_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX corporate_action_listed_asset_id_date ON corporate_action (listed_asset_id, `date`);
CREATE TABLE IF NOT EXISTS listed_asset_position (id INT AUTO_INCREMENT PRIMARY KEY, listed_asset_id INT NOT NULL, `date` DATE NOT NULL, principal DECIMAL(14, 2) NOT NULL, yield DECIMAL(14, 2) NOT NULL, taxes DECIMAL(14, 2) NOT NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_listed_asset_position_listed_asset_id__id FOREIGN KEY (listed_asset_id) REFERENCES listed_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
ALTER TABLE listed_asset_position ADD CONSTRAINT listed_asset_position_listed_asset_id_date_unique UNIQUE (listed_asset_id, `date`);
CREATE TABLE IF NOT EXISTS ticker_catalog (ticker VARCHAR(12) PRIMARY KEY, `name` VARCHAR(150) NOT NULL, kind VARCHAR(10) NOT NULL);
CREATE INDEX ticker_catalog_name ON ticker_catalog (`name`);
