-- Fase 1: the allocation engine (capital, class targets, per-strategy attribution). Generated by
-- ./gradlew :persistence:generateMigrationScript, not hand-written.
CREATE TABLE IF NOT EXISTS capital_snapshot (id INT AUTO_INCREMENT PRIMARY KEY, `date` DATE NOT NULL, external_balance DECIMAL(14, 2) NOT NULL, planned_contribution DECIMAL(14, 2) NOT NULL, created_at DATETIME(6) NOT NULL);
CREATE INDEX capital_snapshot_date ON capital_snapshot (`date`);
CREATE TABLE IF NOT EXISTS asset_class_target (id INT AUTO_INCREMENT PRIMARY KEY, asset_class VARCHAR(20) NOT NULL, weight DECIMAL(7, 4) NOT NULL, effective_from DATE NOT NULL, created_at DATETIME(6) NOT NULL);
CREATE INDEX asset_class_target_asset_class_effective_from ON asset_class_target (asset_class, effective_from);
CREATE TABLE IF NOT EXISTS fixed_income_subclass_target (id INT AUTO_INCREMENT PRIMARY KEY, sub_class VARCHAR(20) NOT NULL, weight DECIMAL(7, 4) NOT NULL, effective_from DATE NOT NULL, created_at DATETIME(6) NOT NULL);
CREATE INDEX fixed_income_subclass_target_sub_class_effective_from ON fixed_income_subclass_target (sub_class, effective_from);
CREATE TABLE IF NOT EXISTS product_classification (product_type VARCHAR(20), product_id INT, asset_class VARCHAR(20) NOT NULL, CONSTRAINT pk_product_classification PRIMARY KEY (product_type, product_id));
CREATE TABLE IF NOT EXISTS strategy (id INT AUTO_INCREMENT PRIMARY KEY, `name` VARCHAR(100) NOT NULL, created_at DATETIME(6) NOT NULL);
CREATE TABLE IF NOT EXISTS attribution_movement (id INT AUTO_INCREMENT PRIMARY KEY, listed_asset_id INT NOT NULL, strategy_id INT NOT NULL, `date` DATE NOT NULL, quantity DECIMAL(18, 8) NOT NULL, reason VARCHAR(20) NOT NULL, note VARCHAR(255) NULL, created_at DATETIME(6) NOT NULL, CONSTRAINT fk_attribution_movement_listed_asset_id__id FOREIGN KEY (listed_asset_id) REFERENCES listed_asset(id) ON DELETE RESTRICT ON UPDATE RESTRICT, CONSTRAINT fk_attribution_movement_strategy_id__id FOREIGN KEY (strategy_id) REFERENCES strategy(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX attribution_movement_listed_asset_id_date ON attribution_movement (listed_asset_id, `date`);
